config/routes.rb
Byop::Application.routes.draw do

  resource :session
  resources :user_menus, :only => [:index]
  resources :manufacturers, :only => [:index, :new, :create, :edit, :update]  
  resources :users do
    resources :user_levels
  end
  resources :customers do
    resources :comm_logs, :only => [:new, :create, :show, :destroy]
  end
  resources :src_plants
  resources :suppliers
  resources :quality_issues, :only  => [:index]
  resources :shipment, :only => [:index]
  resources :projects do
    member do
      put :cancel
      put :re_activate
    end
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results
    end
    resources :project_logs, :only => [:new, :create, :show, :destroy]
    resources :productions, :only => [:index, :new, :create, :edit, :update, :show]
    resources :shipments, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
      end
    end
    
    resources :sourcings, :only => [:index, :new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :purchasings, :only => [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :installations, :only => [:index, :new, :create, :edit, :update] 
    resources :proj_modules, :only => [:new, :create]
    resources :quality_issues, :only => [:new, :create, :edit, :update, :show] 
  end  

  resources :productions do
    resources :production_logs, :only => [:index, :new, :create]
  end
  
  resources :payment_logs, :only =>[:index]
  resources :purchasings do
    collection do
      get :search
      put :search_results
    end     
    resources :purchasing_logs, :only => [:index, :new, :create] 
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  
  resources :sourcings do
    collection do
      get :search
      put :search_results
    end      
    resources :sourcing_logs, :only => [:index, :new, :create]   
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  resources :payment_logs do
    resources :pay_status_logs, :only => [:new, :create]
    member do
      put :approve
      put :stamp_paid
    end
    collection do
      get :search
      put :search_results      
      get :stats
      put :stats_results
    end  
  end
  
  resources :installation_purchases, :only => [:index]  
  resources :installations do
    resources :installation_logs, :only => [:index, :new, :create]
    resources :installation_purchases, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve        
      end
    end          
  end  
  
  resources :installation_purchases do
    member do
      put :warehousing
    end
    resources :installation_purchase_logs, :only => [:new, :create]
  end  
  
  resources :parts do
    resources :out_logs, :only => [:new, :create, :show]
  end
  
  resources :shipments do
    resources :shipment_items, :only => [:index]
  end
  
  resources :shipment_items do
    resources :box_items
  end
  resources :sys_logs, :only => [:index] do
    collection do
      get :sort_by_user_id
      get :sort_by_ip
    end
  end   
  
  root :to => "sessions#new"
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/user_menus', :to => 'user_menus#index'
  match '/view_handler', :to => 'application#view_handler'

end

app/controllers/purchasings_controller.rb
# encoding: utf-8
class PurchasingsController < ApplicationController
  before_filter :require_employee  
  
  helper_method :has_create_right?, :has_show_right?, :has_update_right?, :has_log_right?, :has_stats_right?, :has_delete_right?, :has_reorder_right?,
                :need_approve?, :approved?, :display_approve?, :display_dis_approve?
                
  def index
    @title = '外购计划'
    @project = Project.find(params[:project_id])
    @purchasings = @project.purchasings.order("delivered, created_at DESC, order_date, delivery_date").paginate(:per_page => 40, :page => params[:page])    
  end

  def new
    @title = '输入外购'
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.new()
    if !has_create_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end

  def create
    if has_create_right?
      @project = Project.find(params[:project_id])
      @purchasing = @project.purchasings.new(params[:purchasing], :as => :role_new)
      @purchasing.input_by_id = session[:user_id]
      if @purchasing.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=计划已保存！")
      else
        flash.now[:error] = '数据错误，无法保存！'
        render 'new'
      end
    end
  end

  def edit
    @title = '更改外购'
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if !has_update_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end

  end

  def update
    if has_update_right? 
      @project = Project.find(params[:project_id])
      @purchasing = @project.purchasings.find(params[:id])
      @purchasing.input_by_id = session[:user_id]
      if @purchasing.update_attributes(params[:purchasing], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=计划已更改！")
      else
        flash.now[:error] = '数据错误，无法保存!'
        render 'edit'
      end
      
    end
  end

  def show
    @title = '外购计划内容'
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if !has_show_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end
  
  def destroy
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if !has_delete_right? 
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    else    
      if !approved?(@purchasing) 
        @purchasing.transaction do
          #delete purchasing log
          @purchasing.purchasing_logs.each do |r|
            r.destroy
          end
          #delete payment log
          @purchasing.payment_logs.each do |r|
            r.destroy
          end
          @purchasing.destroy
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=计划已删除！")
        end
      end
    end
  end
  
  def approve
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if need_approve?(@purchasing)
      if is_tech_eng? && @purchasing.eng_id == session[:user_id]
        if @purchasing.update_attributes({:approved_by_eng => true, :approve_eng_id => session[:user_id],
                                       :approve_date_eng => Time.now}, :as => :role_approve_disapprove_stamped)
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已批准！'
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未批准!")
        end
      elsif vp_eng?
        if @purchasing.update_attributes({:approved_by_vp_eng => true, :approve_vp_eng_id => session[:user_id],
                                       :approve_date_vp_eng => Time.now}, :as => :role_approve_disapprove_stamped)  
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已批准！'
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未批准!")
        end                         
      elsif pur_eng?
        if @purchasing.update_attributes({:approved_by_pur_eng => true, :approve_pur_eng_id => session[:user_id],
                                       :approve_date_pur_eng => Time.now}, :as => :role_approve_disapprove_stamped) 
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已批准！'
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未批准!")
        end                               
      elsif ceo?
        if @purchasing.update_attributes({:approved_by_ceo => true, :approve_ceo_id => session[:user_id],
                                       :approve_date_ceo => Time.now}, :as => :role_approve_disapprove_stamped) 
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已批准！'
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未批准!")
        end                             
      end     
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!") 
    end
  end

  def dis_approve
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if need_approve?(@purchasing)
      if is_tech_eng? && @purchasing.eng_id == session[:user_id]
        if @purchasing.update_attributes({:approved_by_eng => false, :approve_eng_id => session[:user_id],
                                       :approve_date_eng => Time.now}, :as => :role_approve_disapprove_stamped)
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已否决！' 
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未否决!")
        end
      elsif vp_eng?
        if @purchasing.update_attributes({:approved_by_vp_eng => false, :approve_vp_eng_id => session[:user_id],
                                       :approve_date_vp_eng => Time.now}, :as => :role_approve_disapprove_stamped)  
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已否决！' 
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未否决!")
        end                
      elsif pur_eng?
        if @purchasing.update_attributes({:approved_by_pur_eng => false, :approve_pur_eng_id => session[:user_id],
                                       :approve_date_pur_eng => Time.now}, :as => :role_approve_disapprove_stamped) 
           redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已否决！' 
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未否决!")
        end                     
      elsif ceo?
        if @purchasing.update_attributes({:approved_by_ceo => false, :approve_ceo_id => session[:user_id],
                                       :approve_date_ceo => Time.now}, :as => :role_approve_disapprove_stamped)
          redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购已否决！' 
        else
          redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=数据错误。外购未否决!")
        end                     
      end       
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!") 
    end
  end

  #re-start the whole process again
  def re_approve
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if ceo?
        @purchasing.update_attributes({:approved_by_eng => nil, :approve_eng_id => nil,:approve_date_eng => nil,
                                       :approved_by_vp_eng => nil, :approve_vp_eng_id => nil, :approve_date_vp_eng => nil,
                                       :approved_by_pur_eng => nil, :approve_pur_eng_id => nil, :approve_date_pur_eng => nil,
                                       :approved_by_ceo => nil, :approve_ceo_id => nil, :approve_date_ceo => nil},
                                       :as => :role_approve_disapprove_stamped)
    
      redirect_to project_purchasing_path(@project, @purchasing), :notice => '外购需要重新批准！'
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!") 
    end
  end
  
  def stamp
    @project = Project.find(params[:project_id])
    @purchasing = @project.purchasings.find(params[:id])
    if comp_sec?
      @purchasing.update_attributes({:stamped => true}, :as => :role_approve_disapprove_stamped)
      redirect_to project_purchasing_path(@project, @purchasing)
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!")       
    end    
  end
  
  def search
    @purchasing = Purchasing.new
  end

  def search_results
    @purchasing = Purchasing.new(params[:purchasing], :as => :role_search_stats)
    @purchasings = @purchasing.find_purchasings.order("project_id DESC, delivered, created_at DESC, order_date, delivery_date") #.paginate(:per_page => 40, :page => params[:page])
    #seach params
    @search_params = search_params()
  end
        
  protected
  
  def need_approve?(purchasing)
    if is_tech_eng? && purchasing.eng_id == session[:user_id] && purchasing.approved_by_pur_eng.nil? && purchasing.approved_by_ceo.nil?  && purchasing.approved_by_vp_eng.nil? 
      return true
    elsif pur_eng? && purchasing.approved_by_eng  && purchasing.approved_by_ceo.nil? && purchasing.approved_by_vp_eng.nil?
      return true
    elsif vp_eng? && purchasing.approved_by_eng && purchasing.approved_by_pur_eng && purchasing.approved_by_ceo.nil?
      return true
    elsif ceo? && purchasing.approved_by_eng  && purchasing.approved_by_pur_eng && purchasing.approved_by_vp_eng
      return true
    end
    return false
  end
 
  def display_approve?(purchasing)
    if is_tech_eng? && purchasing.eng_id == session[:user_id] && (purchasing.approved_by_eng.nil? || !purchasing.approved_by_eng)
      return true
    elsif vp_eng? && (purchasing.approved_by_vp_eng.nil? || !purchasing.approved_by_vp_eng)
      return true

app/helpers/purchasings_helper.rb
module PurchasingsHelper
end

app/views/purchasings/create.html.erb
<h1>Purchasings#create</h1>
<p>Find me in app/views/purchasings/create.html.erb</p>

app/views/purchasings/edit.html.erb
<div id='main_body'>
<h1>修改外购计划</h1>

<%= render 'form' %>

<%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
</div>

app/views/purchasings/index.html.erb
<div id="main_body">
<h1>外购计划-<%=@project.name %></h1>
<div class="byop_pagination"><%= will_paginate %></div>
<table>
  <tr>
    <th>#</th>
    <th>生成日期</th>
    <th>产品名称</th>
    <th>总额（￥）</th>
    <th>客户</th>
    <th>订购日期</th>
    <th>预定到货日期</th>
    <th>实际到货日期</th>
    <th>批准？</th>
    <th>到货?</th>
    <th>来自库存</th>
    <th>供应商</th>
    <th>部件工程师</th>
    <th>外购工程师</th>
    <th></th>
    <th></th> 
    <th></th>
  </tr>

<% @purchasings.each do |pur| %>
  <tr>
  	<td><%= link_to pur.id.to_s, SUBURI + "/view_handler?index=1&url=#{project_purchasing_path(@project, pur)}" if has_show_right? %><%='*' if (pur.created_at + 8.hours) > DAYS_OF_NEW.days.ago %></td>
  	<td><%= (pur.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
    <td><%= pur.prod_name %></td>
    <td><%= number_with_precision(pur.unit_price * pur.qty, :precision => 2) if pur.unit_price.present? && pur.qty.present? %></td>
    <td width='10%'><%= pur.project.customer.short_name %></td>
    <td><%= pur.order_date.strftime("%Y/%m/%d") %></td>
    <td><%= pur.delivery_date.strftime("%Y/%m/%d") if pur.delivery_date.present? %></td>
    <td><%= pur.actual_receiving_date.strftime("%Y/%m/%d") if pur.actual_receiving_date.present? %></td>
    <td><%= yes_no_cn(approved?(pur)) %></td>
    <td><%= yes_no_cn(pur.delivered) %></td>
    <td><%= yes_no_cn(pur.from_warehouse) %></td>
    <td width="10%"><%= pur.supplier.short_name if pur.supplier_id.present? %></td>
    <td><%= pur.eng.name unless pur.eng_id.blank? %></td> 
    <td><%= pur.pur_eng.name unless pur.pur_eng_id.blank? %></td> 
    <td><%= link_to 'Edit', SUBURI + "/view_handler?index=1&url=#{edit_project_purchasing_path(@project, pur)}" if has_update_right? %></td>
    <td><%= link_to '批准', approve_project_purchasing_path(@project, pur), :method => :put if need_approve?(pur) && display_approve?(pur) %></td>
    <td><%= link_to '状态', SUBURI + "/view_handler?index=1&url=#{purchasing_purchasing_logs_path(pur)}" %></td>
  </tr>
<% end %>
</table>
  <%= link_to 'Back', SUBURI + "/view_handler?index=0" %> &nbsp; | &nbsp;
  <%= link_to '输入外购', SUBURI + "/view_handler?index=1&url=#{new_project_purchasing_path(@project)}" if has_create_right? %>
  <%= link_to '搜索', search_purchasings_path %>
  <!--%= link_to '统计', stats_purchasings_path if has_stats_right? %-->
</div>

app/views/purchasings/new.html.erb
<div id='main_body'>
<h1>输入外购计划</h1>

<%= render 'form_new' %>

<%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
</div>

app/views/purchasings/search_results.html.erb
<div id="main_body">
<h1>外购件搜索</h1>
<%=@search_params%>
<% if has_stats_right? %>
<p>总外购产品个数： <%=@purchasings.count %>, 
	总金额￥： <%= number_with_delimiter(number_with_precision(@purchasings.sum('unit_price * qty'), :precision => 2)) %>,
	待批准产品个数： <%= @purchasings.where("approved_by_eng IS NULL OR approved_by_vp_eng IS NULL OR approved_by_pur_eng IS NULL OR approved_by_ceo IS NULL").count %>, 
	未批准产品个数： <%= @purchasings.where("approved_by_eng = ? OR approved_by_vp_eng = ? OR approved_by_pur_eng = ? OR approved_by_ceo =?",false, false, false,false).count %>,
         责任工程师数： <%= @purchasings.select("DISTINCT(eng_id)").count %>, </p>
<p>	已交货个数： <%= @purchasings.where('delivered = ?', true).count  %>,
	已交货金额￥： <%= number_with_delimiter(number_with_precision(@purchasings.where('delivered = ?', true).sum('unit_price * qty'), :precision => 2))  %>,	
	未交货个数： <%= @purchasings.where('delivered = ?', false).count  %>,
	未交货金额￥： <%= number_with_delimiter(number_with_precision(@purchasings.where('delivered = ?', false).sum('unit_price * qty'), :precision => 2))  %>,		 
<p>	已支付金额￥：<%= number_with_delimiter(number_with_precision(@purchasings.joins(:payment_logs).where('payment_logs.paid = ?', true).sum('payment_logs.amount'), :precision => 2)) %>
	未支付金额￥：<%=number_with_delimiter(number_with_precision(@purchasings.sum('unit_price * qty').to_f - @purchasings.joins(:payment_logs).where('payment_logs.paid = ?', true).sum('payment_logs.amount').to_f, :precision => 2)) %><%#= number_with_delimiter(number_with_precision(@purchasings.joins(:payment_logs).where('payment_logs.paid = ?', false).sum('payment_logs.amount'), :precision => 2)) %>
	制造商个数： <%= @purchasings.select("DISTINCT(manufacturer_id)").count %>,          
	供应商个数： <%= @purchasings.select("DISTINCT(supplier_id)").count %>, 
</p>
<% end %>
<table>
  <tr>
    <th>#</th>
    <th>生成日期</th>
    <th>产品名称</th>
    <th>项目名称</th>
    <th>总额（￥）</th>
    <th>客户</th>
    <th>订购日期</th>
    <th>到货日期</th>
    <th>到货?</th>
    <th>工程师</th>
    <th>采购</th>
    <th></th>
    <th></th> 
    <th></th>
  </tr>

<% @purchasings.each do |pur| %>
  <tr>
  	<td><%= link_to pur.id.to_s, SUBURI + "/view_handler?index=1&url=#{project_purchasing_path(pur.project, pur)}" if has_show_right? %><%='*' if (pur.created_at + 8.hours) > DAYS_OF_NEW.days.ago %></td>
  	<td><%= (pur.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
    <td><%= pur.prod_name %></td>
    <td><%= pur.project.name %></td>
    <td><%= number_with_precision(pur.unit_price * pur.qty, :precision => 2) if pur.unit_price.present? && pur.qty.present? %></td>
    <td width="10%"><%= pur.project.customer.short_name %></td>
    <td><%= pur.order_date.strftime("%Y/%m/%d") %></td>
    <td><%= pur.delivery_date.strftime("%Y/%m/%d") if pur.delivery_date.present? %></td>
    <td><%= pur.delivered %></td>
    <td><%= pur.eng.name unless pur.eng_id.blank? %></td> 
    <td><%= pur.pur_eng.name unless pur.pur_eng_id.blank? %></td> 
    <td><%= link_to 'Edit', SUBURI + "/view_handler?index=1&url=#{edit_project_purchasing_path(pur.project, pur)}" if has_update_right? %></td>
    <td><%= link_to '批准', approve_project_purchasing_path(pur.project, pur), :method => :put if need_approve?(pur) %></td>
    <td><%= link_to '状态', SUBURI + "/view_handler?index=1&url=#{purchasing_purchasing_logs_path(pur)}" %></td>
  </tr>
<% end %>
</table>
  <%= link_to 'Back', search_purchasings_path %>

</div>

app/views/purchasings/show.html.erb
<div id="main_body">

<h1>计划内容-<%=@purchasing.prod_name%></h1>

<p>
  <b>项目名称:</b>
  <%= @project.name %>
</p>
<p>
  <b>产品名称:</b>
  <%= @purchasing.prod_name %>
</p>
<p>
  <b>零件#:</b>
  <%= @purchasing.part_num %>
</p>
<p>
  <b>规格:</b>
  <%= @purchasing.spec %>
</p>
<p>
  <b>数量/单位:</b>
  <%= @purchasing.qty %><%= @purchasing.unit %>
</p>
<p>
  <b>单价（￥）:</b>
  <%= @purchasing.unit_price %>
</p>
<p>
  <b>总金额（￥）:</b>
  <%= number_with_precision(@purchasing.unit_price * @purchasing.qty, :precision => 2) if @purchasing.unit_price.present? && @purchasing.qty.present? %>
</p>
<p>	
  <b>已支付额（￥）:</b>
  <%= number_with_precision(@purchasing.payment_logs.where('paid = ?', true).sum("amount"), :precision => 2) %>
</p>
<p>
  <b>制造商:</b>
  <%= @purchasing.manufacturer.name if @purchasing.manufacturer_id.present? %>
</p>
<p>
  <b>供应商:</b>
  <%= @purchasing.supplier.name if @purchasing.supplier_id.present? %>
</p>
<p>
  <b>责任工程师:</b>
  <%= @purchasing.eng.name if @purchasing.eng_id.present? %>
</p>
<p>
  <b>盖章？：</b>
  <%= yes_no_cn(@purchasing.stamped) %>
</p>
<p>
  <b>到货？：</b>
  <%= yes_no_cn(@purchasing.delivered) %>
</p>
<p>
  <b>定购日期:</b>
  <%= @purchasing.order_date.strftime("%Y/%m/%d") %>
</p>
<p>
  <b>预定到货日期:</b>
  <%= @purchasing.delivery_date.strftime("%Y/%m/%d") if @purchasing.delivery_date.present? %>
</p>
<p>
  <b>实际到货日期:</b>
  <%= @purchasing.actual_receiving_date.strftime("%Y/%m/%d") if @purchasing.actual_receiving_date.present? %>
</p>
<p>
  <b>责任工程师批准:</b>
  <%= yes_no_cn(@purchasing.approved_by_eng) %>
</p>
<p>
  <b>审批人:</b>
  <%= @purchasing.approve_eng.name if @purchasing.approve_eng_id.present? && @purchasing.approve_eng_id > 0 %>
</p>
<p>
  <b>审批日期:</b>
  <%= @purchasing.approve_date_eng.strftime("%Y/%m/%d") if @purchasing.approve_date_eng.present? %>
</p>
<p>
  <b>工程付总批准:</b>
  <%= yes_no_cn(@purchasing.approved_by_vp_eng) %>
</p>
<p>
  <b>审批人:</b>
  <%= @purchasing.approve_vp_eng.name if @purchasing.approve_vp_eng_id.present? && @purchasing.approve_vp_eng_id > 0 %>
</p>
<p>
  <b>审批日期:</b>
  <%= @purchasing.approve_date_vp_eng.strftime("%Y/%m/%d") if @purchasing.approve_date_vp_eng.present? %>
</p>
<p>
  <b>采购工程师批准:</b>
  <%= yes_no_cn(@purchasing.approved_by_pur_eng) %>
</p>
<p>
  <b>审批人:</b>
  <%= @purchasing.approve_pur_eng.name if @purchasing.approve_pur_eng_id.present? %>
</p>
<p>
  <b>审批日期:</b>
  <%= @purchasing.approve_date_pur_eng.strftime("%Y/%m/%d") if @purchasing.approve_date_pur_eng.present? %>
</p>
<p>
  <b>厂长批准:</b>
  <%= yes_no_cn(@purchasing.approved_by_ceo) %>
</p>
<p>
  <b>审批人:</b>
  <%= @purchasing.approve_ceo.name if @purchasing.approve_ceo_id.present? %>
</p>
<p>
  <b>审批日期:</b>
  <%= @purchasing.approve_date_ceo.strftime("%Y/%m/%d") if @purchasing.approve_date_ceo.present? %>
</p>
<p>
  <b>输入/更改人:</b>
  <%= @purchasing.input_by.name %>
</p>
<p>
  <b>状态Log:</b>	
  <ul>
<% @purchasing.purchasing_logs.order("id DESC").each do |f| %>
  <li>
  <%= link_to f.created_at.strftime("%Y-%m-%d").to_s + ', ' + f.input_by.name + ', '+ f.log[0..40], SUBURI + "/view_handler?index=1&url=#{purchasing_purchasing_logs_path(f.purchasing_id, f.id)}" %>
  </li>
<% end %>
</ul>
</p>

<%= link_to 'Back', SUBURI + "/view_handler?index=0", :id => 'close' %>
<%= link_to '盖章', stamp_project_purchasing_path(@project, @purchasing), :method => :put, :id => 'purchasing_stamp', :confirm => '盖章外购' + @purchasing.prod_name + '?' if comp_sec? && !@purchasing.stamped %>
<%= link_to '批准采购', approve_project_purchasing_path(@project, @purchasing), :method => :put, :id => 'purchasing_need_approve', :confirm => '批准采购' + @purchasing.prod_name + '?' if need_approve?(@purchasing) && display_approve?(@purchasing) %>
<%= link_to '否决采购', dis_approve_project_purchasing_path(@project, @purchasing), :method => :put, :id => 'purchasing_need_dis_approve', :confirm => '否决采购' + @purchasing.prod_name + '?' if need_approve?(@purchasing) && display_dis_approve?(@purchasing) %>
<%= link_to '重新采购', re_approve_project_purchasing_path(@project, @purchasing), :method => :put, :id => 'purchasing_need_re_approve', :confirm => '重新采购' + @purchasing.prod_name + '?'  if ceo? %>
<%= link_to '付款记录', purchasing_payment_logs_path(@purchasing), :id => 'purchasing_payment_log' if pur_eng? || comp_sec? || vp_eng? || coo? || vp_sales? || ceo? %>
<%= link_to '输入Log', new_purchasing_purchasing_log_path(@purchasing, :format => :js), :remote => true, :id => 'new_log_link' if has_log_right? %>
<%= link_to '删除', project_purchasing_path(@project, @purchasing), :method => :delete, :confirm => '删除' + @purchasing.prod_name + '?', :id => 'destroy_link' if has_delete_right? && !approved?(@purchasing) %>

</div>

app/views/purchasings/update.html.erb
<h1>Purchasings#update</h1>
<p>Find me in app/views/purchasings/update.html.erb</p>