config/routes.rb
Byop::Application.routes.draw do

  resource :session
  resources :user_menus, :only => [:index]
  resources :manufacturers, :only => [:index, :new, :create, :edit, :update]  
  resources :users do
    resources :user_levels
  end
  resources :customers do
    resources :comm_logs, :only => [:new, :create, :show, :destroy]
  end
  resources :src_plants
  resources :suppliers
  resources :quality_issues, :only  => [:index]
  resources :shipment, :only => [:index]
  resources :projects do
    member do
      put :cancel
      put :re_activate
    end
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results
    end
    resources :project_logs, :only => [:new, :create, :show, :destroy]
    resources :productions, :only => [:index, :new, :create, :edit, :update, :show]
    resources :shipments, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
      end
    end
    
    resources :sourcings, :only => [:index, :new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :purchasings, :only => [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :installations, :only => [:index, :new, :create, :edit, :update] 
    resources :proj_modules, :only => [:new, :create]
    resources :quality_issues, :only => [:new, :create, :edit, :update, :show] 
  end  

  resources :productions do
    resources :production_logs, :only => [:index, :new, :create]
  end
  
  resources :payment_logs, :only =>[:index]
  resources :purchasings do
    collection do
      get :search
      put :search_results
    end     
    resources :purchasing_logs, :only => [:index, :new, :create] 
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  
  resources :sourcings do
    collection do
      get :search
      put :search_results
    end      
    resources :sourcing_logs, :only => [:index, :new, :create]   
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  resources :payment_logs do
    resources :pay_status_logs, :only => [:new, :create]
    member do
      put :approve
      put :stamp_paid
    end
    collection do
      get :search
      put :search_results      
      get :stats
      put :stats_results
    end  
  end
  
  resources :installation_purchases, :only => [:index]  
  resources :installations do
    resources :installation_logs, :only => [:index, :new, :create]
    resources :installation_purchases, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve        
      end
    end          
  end  
  
  resources :installation_purchases do
    member do
      put :warehousing
    end
    resources :installation_purchase_logs, :only => [:new, :create]
  end  
  
  resources :parts do
    resources :out_logs, :only => [:new, :create, :show]
  end
  
  resources :shipments do
    resources :shipment_items, :only => [:index]
  end
  
  resources :shipment_items do
    resources :box_items
  end
  resources :sys_logs, :only => [:index] do
    collection do
      get :sort_by_user_id
      get :sort_by_ip
    end
  end   
  
  root :to => "sessions#new"
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/user_menus', :to => 'user_menus#index'
  match '/view_handler', :to => 'application#view_handler'

end

app/controllers/user_menus_controller.rb
class UserMenusController < ApplicationController
  
  before_filter :require_signin
  helper_method :is_worker?
  
  def index  
    #set session vars for viewing history
    session[:page_step] = 1
    session[:page1] = user_menus_path
    render 'user_menus/index'
  end 
  
  protected
  
  def is_worker?
    employee? || qc_eng? || mech_eng? or elec_eng? or hydr_eng? or pur_eng? or inst_eng? or src_eng? or comp_sec? or acct? or warehouse? or coo? or vp_eng? or vp_sales? or ceo?
  end

end

app/helpers/user_menus_helper.rb
module UserMenusHelper
end

app/views/user_menus/_admin.html.erb
<div id="admin">
	<ul>
		<li><%= link_to '用户管理', SUBURI + "/view_handler?index=1&url=#{users_path}" %></li>
		<li><%= link_to '查看系统记录', SUBURI + "/view_handler?index=1&url=#{sys_logs_path}" %></li>
	</ul>
</div>

app/views/user_menus/_employee.html.erb
<div id="tabs">
	<ul>
		<% if admin? %>
		<li><a href="#admin"><span>系统管理</span></a></li><% end %>
		<% if is_worker?  %>
		<li><a href="#user"><span>用户菜单</span></a></li><% end %>
		<% if ceo? or coo? or comp_sec? %>
		<li><a href="#management"><span>统计</span></a></li><% end %>
	</ul>
	<%= render 'admin' if admin? %>
	<%= render 'user' if is_worker? %>
	<%= render 'management' if ceo? or coo? or comp_sec? %>
</div>

app/views/user_menus/_management.html.erb
<div id="manager">
	<ul>
		<li><%= link_to '营运统计', '#' %></li>
		<li><%= link_to '查看系统记录', SUBURI + "/view_handler?index=1&url=#{sys_logs_path}" %></li>
	</ul>
</div>

app/views/user_menus/_user.html.erb
<div id="user">
	<table width="90%">
		<tr>
			<td width="40%" valign="top">
				<ul>
					<li><%= link_to '项目', SUBURI + "/view_handler?index=1&url=#{projects_path}" %></li>					
                    <li><%= link_to '外协厂家', SUBURI + "/view_handler?index=1&url=#{src_plants_path}" %></li>
                    <li><%= link_to '制造商', SUBURI + "/view_handler?index=1&url=#{manufacturers_path}" %></li>
                    <li><%= link_to '质量问题', SUBURI + "/view_handler?index=1&url=#{quality_issues_path}" %></li>
                    <li><%= link_to '外购/协付款记录', SUBURI + "/view_handler?index=1&url=#{payment_logs_path}" if acct? || pur_eng? || src_eng? || vp_eng? || comp_sec? || vp_sales? || coo? || ceo? %></li>
				</ul>
				</td>
				<td width="20">&nbsp;</td>
				<td valign="top">
				<ul>
					<li><%= link_to '客户', SUBURI + "/view_handler?index=1&url=#{customers_path}" %></li>
					<li><%= link_to '物料库存', SUBURI + "/view_handler?index=1&url=#{parts_path}"%></li>
					<li><%= link_to '供应商', SUBURI + "/view_handler?index=1&url=#{suppliers_path}" %></li>
					<li><%= link_to '安装物料', SUBURI + "/view_handler?index=1&url=#{installation_purchases_path}"%></li>
					<li><%= link_to '产品运输', SUBURI + "/view_handler?index=1&url=#{shipments_path}"%></li>
				</ul>
			</td>
		</tr>
	</table>	
</div>

app/views/user_menus/index.html.erb
<%= render 'employee' if employee? %>
<%= render 'src_plant' if src_plant? %>