config/routes.rb
Byop::Application.routes.draw do

  resource :session
  resources :user_menus, :only => [:index]
  resources :manufacturers, :only => [:index, :new, :create, :edit, :update]  
  resources :users do
    resources :user_levels
  end
  resources :customers do
    resources :comm_logs, :only => [:new, :create, :show, :destroy]
  end
  resources :src_plants
  resources :suppliers
  resources :quality_issues, :only  => [:index]
  resources :shipment, :only => [:index]
  resources :projects do
    member do
      put :cancel
      put :re_activate
    end
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results
    end
    resources :project_logs, :only => [:new, :create, :show, :destroy]
    resources :productions, :only => [:index, :new, :create, :edit, :update, :show]
    resources :shipments, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
      end
    end
    
    resources :sourcings, :only => [:index, :new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :purchasings, :only => [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :installations, :only => [:index, :new, :create, :edit, :update] 
    resources :proj_modules, :only => [:new, :create]
    resources :quality_issues, :only => [:new, :create, :edit, :update, :show] 
  end  

  resources :productions do
    resources :production_logs, :only => [:index, :new, :create]
  end
  
  resources :payment_logs, :only =>[:index]
  resources :purchasings do
    collection do
      get :search
      put :search_results
    end     
    resources :purchasing_logs, :only => [:index, :new, :create] 
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  
  resources :sourcings do
    collection do
      get :search
      put :search_results
    end      
    resources :sourcing_logs, :only => [:index, :new, :create]   
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  resources :payment_logs do
    resources :pay_status_logs, :only => [:new, :create]
    member do
      put :approve
      put :stamp_paid
    end
    collection do
      get :search
      put :search_results      
      get :stats
      put :stats_results
    end  
  end
  
  resources :installation_purchases, :only => [:index]  
  resources :installations do
    resources :installation_logs, :only => [:index, :new, :create]
    resources :installation_purchases, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve        
      end
    end          
  end  
  
  resources :installation_purchases do
    member do
      put :warehousing
    end
    resources :installation_purchase_logs, :only => [:new, :create]
  end  
  
  resources :parts do
    resources :out_logs, :only => [:new, :create, :show]
  end
  
  resources :shipments do
    resources :shipment_items, :only => [:index]
  end
  
  resources :shipment_items do
    resources :box_items
  end
  resources :sys_logs, :only => [:index] do
    collection do
      get :sort_by_user_id
      get :sort_by_ip
    end
  end   
  
  root :to => "sessions#new"
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/user_menus', :to => 'user_menus#index'
  match '/view_handler', :to => 'application#view_handler'

end

app/models/project.rb
# encoding: utf-8
class Project < ActiveRecord::Base
  
  attr_accessor   :customer_id_search, :start_date_search, :end_date_search, :awarded_search, :cancelled_search, 
                  :completed_search, :time_frame, :project_manager_id_s
  
  attr_accessible :customer_id_search, :start_date_search, :end_date_search, :awarded_search, :completed_search, :cancelled_search,
                  :time_frame, :project_manager_id_s, :as => :role_search_stats
  
  attr_accessible :name, :customer_id, :status, :install_address, :budget, :tech_spec, 
                  :bid_doc_available_date, :bid_deadline, :bid_opening_date, :contract_date,
                  :production_start_date,  :note, :customer_contact_info, :awarded, :project_manager_id,
                  :as => :role_new
  attr_accessible :name,       :status, :install_address, :budget, :tech_spec, :subsys_spec, :other_tech_requirement, 
                  :construction_requirement, :turn_over_requirement, :bid_doc_available_date, :bid_deadline, :bid_opening_date, :contract_date,
                  :production_start_date, :construction_finish_date, :install_start_date, :note, :customer_contact_info,
                  :review_after, :completed, :cancelled, :awarded, :design_start_date, :project_manager_id,
                  :as => :role_update    
                                
  belongs_to :input_by, :class_name => 'User'
  belongs_to :customer
  belongs_to :project_manager, :class_name => 'User'
  has_many :project_logs
  has_many :productions
  has_many :sourcings
  has_many :purchasings
  has_many :installations
  has_many :proj_modules
  has_many :quality_issues
  has_many :shipments
  
  validates :name, :presence => true, :uniqueness => true
  validates_numericality_of :customer_id, :greater_than => 0
  validates :status, :presence => true
  validates :tech_spec, :presence => true
  validates :customer_contact_info, :presence => true
   
  scope :not_cancelled_project, where(:cancelled => false)
  scope :cancelled_project, where(:cancelled => true) 
  scope :completed_project, where(:completed => true) 
  scope :ongoing_project, where(:completed => false, :cancelled => false) 
  
  def find_projects
    projects = Project.where('created_at > ?', 6.years.ago).order('created_at DESC')
    projects = projects.where('awarded = ?', true) if awarded_search.present? && awarded_search == 'true'
    projects = projects.where('awarded = ? OR awarded IS NULL', false) if awarded_search.present? && awarded_search == 'false'
    projects = projects.where('completed = ?', true) if completed_search.present? && completed_search == 'true'
    projects = projects.where('completed = ?', false) if completed_search.present? && completed_search == 'false'
    projects = projects.where('cancelled = ?', false) if cancelled_search.present? && cancelled_search == 'false'
    projects = projects.where('cancelled = ?', true) if cancelled_search.present? && cancelled_search == 'true'
    projects = projects.where('created_at > ?', start_date_search) if start_date_search.present?
    projects = projects.where('created_at < ?', end_date_search) if end_date_search.present?
    projects = projects.where("customer_id = ?", customer_id_search) if customer_id_search.present?
    projects
  end  
                 
end

 

app/controllers/projects_controller.rb
# encoding: utf-8
class ProjectsController < ApplicationController
  before_filter :require_signin
  before_filter :require_employee  
  
  helper_method :has_create_right?, :has_show_right?, :has_update_right?, :has_log_right?, :has_search_right?, :has_stats_right?, :is_project_manager?
  
  def index
    @title = '项目设备'
    if comp_sec? || vp_eng? || vp_sales? || ceo? || coo?
      @projects = Project.order("id DESC, created_at DESC, completed ASC").paginate(:per_page => 40, :page => params[:page])    
    else
      @projects = Project.not_cancelled_project.order("id DESC").paginate(:per_page => 40, :page => params[:page])
    end
  end

  def new
    @title = '输入项目设备'
    @project = Project.new()
    if !has_create_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end

  def create
    if has_create_right?
      @project = Project.new(params[:project], :as => :role_new)
      @project.input_by_id = session[:user_id]
      if @project.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=项目设备信息已保存！")
      else
        flash.now[:error] = '数据错误，无法保存！'
        render 'new'
      end
    end
  end

  def edit
    @title = '更改项目设备'
    @project = Project.find(params[:id])
    if !has_update_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end

  def update
    if has_update_right?
      @project = Project.find(params[:id])
      @project.input_by_id = session[:user_id]
      if @project.update_attributes(params[:project], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=项目设备信息已更改！")
      else
        flash.now[:error] = '数据错误，无法保存!'
        render 'edit'
      end
    end
  end

  def show
    @title = '项目设备内容'
    @project = Project.find(params[:id])
    if !has_show_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end
  
  def cancel
    if ceo?
      @project = Project.find(params[:id])
      @project.update_attributes({:cancelled => true, :cancel_date => Time.now, :input_by_id => session[:user_id]},
                                 :as => :role_update ) 
    end
  end
  
  def re_activate
    if ceo?
      @project = Project.find(params[:id])
      @project.update_attributes({:cancelled => false, :cancel_date => Time.now, :input_by_id => session[:user_id]},
                                 :as => :role_update ) 
    end
  end  
  
  def search
    if has_search_right?
      @project = Project.new
    end
  end
  
  def search_results
    if has_search_right?
      @project = Project.new(params[:project], :as => :role_search_stats)
      @projects = @project.find_projects
      #seach params
      @search_params = search_params()
    end
  end
  
  def stats
    if has_stats_right?
      @project = Project.new
    end
  end
  
  def stats_results
    if has_stats_right?
      @project = Project.new(params[:project], :as => :role_search_stats)
      @project_stats = @project.find_projects
      #retrieve parameter
      @stats_params = "参数：" + params[:project][:time_frame] + '，统计条数：' + @project_stats.count.to_s 
      group_records(params[:project][:time_frame]) #result in @lease_usage_record_stats & @stats_params
      @stats_params += ', ' + Customer.find_by_id(params[:project][:customer_id_search]).short_name if params[:project][:customer_id_search].present?
      @stats_params += ', 签了？：' + params[:project][:awarded_search] if params[:project][:awarded_search].present?
      @stats_params += ', 取消？：' + params[:project][:cancelled_search] if params[:project][:cancelled_search].present?
      @stats_params += ', 完成？：' + params[:project][:completed_search] if params[:project][:completed_search].present?
      return if @project_stats.blank?  #empty record causes error in following code      
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=无统计权限！")      
    end
  end
      
  protected
  
  def has_search_right?
    comp_sec? || vp_eng? || vp_sales? || coo? || ceo?
  end
  
  def has_stats_right?
    vp_sales? || coo? || ceo?
  end
  
  def has_show_right?
    is_eng? || acct? || comp_sec? || vp_eng? || vp_sales? || coo? || ceo?
  end
  
  def has_create_right?
    comp_sec? || vp_sales? || coo? || ceo?
  end
  
  def has_update_right?
    inst_eng? || vp_eng? || comp_sec? || vp_sales? || coo? || ceo?
  end
  
  def is_project_manager?(project)
    project.project_manager_id == session[:user_id] 
  end
  
  def has_log_right?
    comp_sec? || vp_sales? || coo? || ceo?
  end
  
  def search_params
    search_params = "参数："
    search_params += ' 开始日期：' + params[:project][:start_date_search] if params[:project][:start_date_search].present?
    search_params += ', 结束日期：' + params[:project][:end_date_search] if params[:project][:end_date_search].present?
    search_params += ', 项目签了？ ：' + params[:project][:awarded_search] if params[:project][:awarded_search].present?
    search_params += ', 项目取消？ ：' + params[:project][:cancelled_search] if params[:project][:cancelled_search].present?
    search_params += ', 项目完成？ ：' + params[:project][:completed_search] if params[:project][:completed_search].present?
    search_params += ', 客户 ：' + Customer.find_by_id(params[:project][:customer_id_search].to_i).short_name if params[:project][:customer_id_search].present?
    search_params
  end

  def group_records(time_frame)
      case time_frame #params[:lease_usage_record][:time_frame]
      when '周'
        @project_stats = @project_stats.where("created_at > ?", 2.years.ago).all(:select => "created_at, sum(budget) as revenue, count(DISTINCT(customer_id)) as num_customer", 
                                :group => "strftime('%Y/%W', created_at)")
                          
      when '月'
        @project_stats = @project_stats.where("created_at > ?", 3.years.ago).all(:select => "created_at, sum(budget) as revenue, count(DISTINCT(customer_id)) as num_customer", 
                                :group => "strftime('%Y/%m', created_at)")                     
      when '季'
        @project_stats = @project_stats.where("created_at > ?", 4.years.ago).all(:select => "created_at, sum(budget) as revenue, count(DISTINCT(customer_id)) as num_customer,
                                CASE WHEN cast(strftime('%m', created_at) as integer) BETWEEN 1 AND 3 THEN 1 WHEN cast(strftime('%m', created_at) as integer) BETWEEN 4 and 6 THEN 2 WHEN cast(strftime('%m', created_at) as integer) BETWEEN 7 and 9 THEN 3 ELSE 4 END as quarter", 
                                :group => "strftime('%Y', created_at), quarter")                                
      when '年'
        @project_stats = @project_stats.where("created_at > ?", 5.years.ago).all(:select => "created_at, sum(budget) as revenue, count(DISTINCT(customer_id)) as num_customer",
                                :group => "strftime('%Y', created_at)")     
      end   

  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form_eng_vp.html.erb
<%= simple_form_for @project do |f| %>    
 
  <%= f.input :customer_id, :label => '客户:', :readonly => true, :required => false, :input_html => {:value => @project.customer.name} %>
  <%= f.input :name, :label => '项目名称：', :readonly => true, :required => false, :input_html => {:value => @project.name} %>  
  <%= f.input :customer_contact_info, :label => '联系信息：', :hint => '联系人及电话', :input_html => { :rows => 4, :readonly => true} %> 
  <%= f.input :awarded, :label => '签合同了？：', :collection => return_yes_no, :include_blank => true %>   
  <%= f.input :status, :label => '项目状态：', :collection => return_project_status %>
  <%= f.input :install_address, :label => '设备安装地点：' %> 
  <%= f.input :tech_spec, :label => '技术参数：', :input_html => { :rows => 8} %> 
  <%= f.input :tonnage, :label => '设备吨位：', :as => :string %>     
  <%= f.input :subsys_spec, :label => '部件技术：', :input_html => { :rows => 8} %>      
  <%= f.input :other_tech_requirement, :label => '其他技术：', :input_html => { :rows => 6} %>     
  <%= f.input :construction_finish_date, :label => '土建完成日期：', :as => :string %>  
  <%= f.input :production_start_date, :label => '生产开始日期：', :as => :string %>
  <%= f.input :design_start_date, :label => '设计开始日期：', :as => :string %>   
  <%= f.input :install_start_date, :label => '安装开始日期：', :as => :string, :input_html => {:readonly => true} %>   
  <%= f.input :turn_over_requirement, :label => '验收交付：', :input_html => { :rows => 4} %>  
  <%= f.input :completed, :label => '完成？：', :as => :radio %> 
  <%= f.input :cancelled, :label => '项目取消？:', :readonly => true, :required => false, :as => :string,:input_html => {:value => yes_no_cn(@project.cancelled)} %>        
  <%= f.input :note, :label => '注释：', :input_html => { :rows => 4} %>
  <%= f.input :review_after, :label => '项目总结：', :input_html => {:rows => 6} %>          
  
  <%= f.button :submit, '保存' %>  
<% end %>  

app/views/projects/_form_inst_eng.html.erb
<%= simple_form_for @project do |f| %>    
 
  <%= f.input :customer_id, :label => '客户:', :readonly => true, :required => false, :input_html => {:value => @project.customer.name} %>
  <%= f.input :name, :label => '项目名称：', :readonly => true, :required => false, :input_html => {:value => @project.name} %>  
  <%= f.input :status, :label => '项目状态：', :readonly => true, :required => false, :input_html => {:value => @project.status} %>
  <%= f.input :install_start_date, :label => '安装开始日期：', :as => :string %>   
  <%= f.input :turn_over_requirement, :label => '验收交付：', :input_html => { :rows => 4} %>         
  
  <%= f.button :submit, '保存' %>  
<% end %>  

app/views/projects/index.html.erb
<div id="main_body">
<h1>设备项目</h1>
<div class="byop_pagination"><%= will_paginate %></div>
<table>
  <tr>
    <th>#</th>
    <th>生成日期</th>
    <th>项目名称</th>
    <th>客户</th>
    <th>项目状态</th> 
    <th>完成?</th>
    <th></th>
    <th></th> 
    <th></th> 
    <th></th> 
    <th></th> 
    <th></th>
  </tr>

<% @projects.each do |proj| %>
  <tr>
  	<td><%= link_to proj.id.to_s, SUBURI + "/view_handler?index=1&url=#{project_path(proj)}" if has_show_right? %><%='*' if (proj.created_at + 8.hours) > DAYS_OF_NEW.days.ago %></td>
  	<td><%= (proj.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
    <td><%= proj.name %></td>
    <td><%= proj.customer.name %></td>
    <td><%= proj.status %></td>
    <td><%= yes_no_cn(proj.completed) %></td>  
    <td><%= link_to 'Edit', SUBURI + "/view_handler?index=1&url=#{edit_project_path(proj)}" if has_update_right? || is_project_manager?(proj) %></td>
    <% if proj.awarded %>
      <td><%= link_to '计划', SUBURI + "/view_handler?index=1&url=#{project_productions_path(proj)}" %></td>
      <td><%= link_to '外协', SUBURI + "/view_handler?index=1&url=#{project_sourcings_path(proj)}" %></td>
      <td><%= link_to '外购', SUBURI + "/view_handler?index=1&url=#{project_purchasings_path(proj)}" %></td>
      <td><%= link_to '安装', SUBURI + "/view_handler?index=1&url=#{project_installations_path(proj)}" %></td>
      <td><%= link_to '质量', SUBURI + "/view_handler?index=1&url=#{quality_issues_path(proj)}" %></td>
    <% end %>
  </tr>
<% end %>
</table>
  <%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
  &nbsp;<%= link_to '输入项目', SUBURI + "/view_handler?index=1&url=#{new_project_path}" if has_create_right? %>
  <%= link_to '搜索', search_projects_path if has_search_right? %>
  <%= link_to '统计', stats_projects_path if has_stats_right? %>

</div>

app/views/projects/search.html.erb
<div id="main_body">
<h1>项目搜索</h1>
<%= simple_form_for @project, :method => :put, :url => search_results_projects_path do |f| %>    
  <%= f.input :start_date_search, :label => "生成开始日期 ：", :as => :string, :input_html => {:size => 40} %>
  <%= f.input :end_date_search, :label => "生成结束日期 ：", :as => :string, :input_html => {:size => 40} %>
  <%= f.input :customer_id_search, :collection => Customer.active_cust.order('name'), :label_method => :name, :value_method => :id, :prompt => "选客户", :label => "客户 ："  %>
  <%= f.input :awarded_search, :label => "项目签了？ ：", :collection => [['Yes',true], ['No', false]], :include_blank => true %> 
  <%= f.input :completed_search, :label => "项目完成？ ：", :collection => [['Yes',true], ['No', false]], :include_blank => true %>   
  <%= f.input :cancelled_search, :label => "项目取消？ ：", :collection => [['Yes',true], ['No', false]], :include_blank => true %>
  <%= f.button :submit, '搜索' %>  
<% end %> 
</div>

app/views/projects/search_results.html.erb
<div id="main_body">
<h1>设备项目搜索</h1>
<%=@search_params%>
<% if has_stats_right? %>
<p>总单数： <%=@projects.count %>, 
	总金额￥： <%= number_with_delimiter(@projects.sum('budget')) %>, 
	客户数量： <%= @projects.select("DISTINCT(customer_id)").count %>,</p>
<p>	完成项目数： <%= @projects.where('completed = ?', true).count %>, 
	完成金额￥： <%= number_with_delimiter(@projects.where('completed = ?', true).sum('budget'))  %>,	
	待签项目数： <%= @projects.where('awarded IS NULL').count %>,
	待签金额￥： <%= number_with_delimiter(@projects.where('awarded IS NULL').sum('budget')) %>,</p>		 
<p>	流标项目数： <%= @projects.where('awarded = ?', false).count %>,         
	流标金额￥： <%= number_with_delimiter(@projects.where('awarded = ?', false).sum('budget')) %>, 
	取消项目数： <%= @projects.where('cancelled = ?', true).count %>, 
	取消金额￥： <%= number_with_delimiter(@projects.where('cancelled = ?', true).sum('budget')) %>，
</p>
<% end %>
<table>
  <tr>
    <th>#</th>
    <th>生成日期</th>
    <th>项目名称</th>
    <th>客户</th>
    <th>项目状态</th> 
    <th>完成?</th>
    <th></th>
    <th></th> 
    <th></th> 
    <th></th> 
    <th></th> 
    <th></th>
  </tr>

<% @projects.each do |proj| %>
  <tr>
  	<td><%= link_to proj.id.to_s, SUBURI + "/view_handler?index=1&url=#{project_path(proj)}" if has_show_right? %><%='*' if (proj.created_at + 8.hours) > DAYS_OF_NEW.days.ago %></td>
  	<td><%= (proj.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
    <td><%= proj.name %></td>
    <td><%= proj.customer.name %></td>
    <td><%= proj.status %></td>
    <td><%= proj.completed %></td>  
    <td><%= link_to 'Edit', SUBURI + "/view_handler?index=1&url=#{edit_project_path(proj)}" if has_update_right? %></td>
    <% if proj.awarded %>
      <td><%= link_to '计划', SUBURI + "/view_handler?index=1&url=#{project_productions_path(proj)}" %></td>
      <td><%= link_to '外协', SUBURI + "/view_handler?index=1&url=#{project_sourcings_path(proj)}" %></td>
      <td><%= link_to '外购', SUBURI + "/view_handler?index=1&url=#{project_purchasings_path(proj)}" %></td>
      <td><%= link_to '安装', SUBURI + "/view_handler?index=1&url=#{project_installations_path(proj)}" %></td>
      <td><%= link_to '质量', SUBURI + "/view_handler?index=1&url=#{quality_issues_path(proj)}" %></td>
    <% end %>
  </tr>
<% end %>
</table>
  <%= link_to 'Back', search_projects_path %>
  &nbsp;<%= link_to '输入项目', SUBURI + "/view_handler?index=1&url=#{new_project_path}" if has_create_right? %>

</div>

app/views/projects/show.html.erb
<div id="main_body">

<h1>项目设备</h1>

<p>
  <b>项目名称:</b>
  <%= @project.name %>
</p>
<p>
  <b>客户:</b>
  <%= @project.customer.name %>
</p>
<p>
  <b>项目经理:</b>
  <%= @project.project_manager.name if @project.project_manager_id.present? %>
</p>
<p>
  <b>项目完成？:</b>
  <%= yes_no_cn(@project.completed) %>
</p>
<p>
  <b>项目取消？:</b>
  <%= yes_no_cn(@project.cancelled) %>
</p>
<% if @project.cancelled %>
  <p>
    <b>项目取消日期:</b>
    <%= @project.cancel_date %>
  </p>
<% end %>
<p>
  <b>签合同了？:</b>
  <%= yes_no_cn(@project.awarded) %>
</p>
<p>
  <b>项目状态:</b>
  <%= @project.status %>
</p>
<p>
  <b>安装地点:</b>
  <%= @project.install_address %>
</p>
<p>
  <b>设备吨位:</b>
  <%= @project.tonnage %>
</p>
<p>
  <b>技术参数:</b>
  <%= @project.tech_spec %>
</p>
<p>
  <b>部件技术</b>
  <%= @project.subsys_spec %>
</p>
<p>
  <b>其他技术:</b>
  <%= @project.other_tech_requirement %>
</p>
<p>
  <b>验收交付:</b>
  <%= @project.turn_over_requirement %>
</p>
<p>
  <b>设计开始日期</b>
  <%= @project.design_start_date.strftime("%Y/%m/%d") unless @project.design_start_date.nil? %>
</p>
<p>
  <b>生产开始日期</b>
  <%= @project.production_start_date.strftime("%Y/%m/%d") unless @project.production_start_date.nil? %>
</p>
<p>
  <b>客户土建完成日期</b>
  <%= @project.construction_finish_date.strftime("%Y/%m/%d") unless @project.construction_finish_date.nil? %>
</p>
<p>
  <b>设备安装开始日期</b>
  <%= @project.install_start_date.strftime("%Y/%m/%d") unless @project.install_start_date.nil? %>
</p>
<p>
  <b>注释:</b>
  <%= @project.note %>
</p>
<p>
  <b>输入/更改:</b>
  <%= @project.input_by.name %>
</p>
<p>
  <b>项目部件:</b>	
  <ol>
 <% @project.proj_modules.order("created_at DESC").each do |f| %>
   <li>
     <%= f.name %>&nbsp;<%= f.created_at.strftime("%Y-%m-%d")%>
   </li>
 <% end %>
  </ol>
</p>
<% if has_create_right? %>
  <p>
    <b>联系信息:</b>
    <%= @project.customer_contact_info %>
  </p>
  <p>
    <b>合同金额（￥）</b>
    <%= number_with_delimiter(number_with_precision(@project.budget, :precision => 2)) %>
  </p>
  <p>
    <b>发放标书日期:</b>
    <%= @project.bid_doc_available_date.strftime("%Y/%m/%d") unless @project.bid_doc_available_date.nil? %>
  </p>
  <p>
    <b>投标截止日期:</b>
    <%= @project.bid_deadline.strftime("%Y/%m/%d") unless @project.bid_deadline.nil? %>
  </p>
  <p>
    <b>开标日期:</b>
    <%= @project.bid_opening_date.strftime("%Y/%m/%d") unless @project.bid_opening_date.nil? %>
  </p>
  <p>
    <b>合同日期</b>
    <%= @project.contract_date.strftime("%Y/%m/%d") unless @project.contract_date.nil? %>
  </p>
  <p>
    <b>项目联系Log:</b>	
    <ul>
  <% @project.project_logs.order("created_at DESC").each do |f| %>
    <li>
    <%= link_to "关于:" + f.subject + ", " + f.created_at.strftime("%Y-%m-%d").to_s, project_project_log_path(f.project_id, f.id, :format => :js), :remote => true %>
    </li>
  <% end %>
  </ul>
  </p>
<% end %>

<%= link_to 'Back', SUBURI + "/view_handler?index=0", :id => 'close' %>
<%= link_to '取消项目', cancel_project_path(@project), :method => :put if ceo? && !@project.cancelled %>
<%= link_to '激活项目', re_activate_project_path(@project), :method => :put if ceo? && @project.cancelled %>
<%= link_to '发运产品', new_project_shipment_path(@project), :id => 'new_shipment_link' if (src_eng? || pur_eng?) && !@project.cancelled %>
<%= link_to '生成部件', new_project_proj_module_path(@project, :format => :js), :remote => true, :id => 'new_module_link' if vp_eng? %>
<%= link_to '报告质量问题', new_project_quality_issue_path(@project) %>
<%= link_to '输入Log', new_project_project_log_path(@project, :format => :js), :remote => true, :id => 'new_log_link' if has_log_right? %>

</div>

app/views/projects/stats_results.html.erb
<div id="main_body">
	<h1>项目统计</h1>
<p><%= @stats_params %></p>
<table>
  <tr>
    <th>时段</th>
    <th>金额（￥）</th>
    <th>客户数</th>
  </tr>
  <% @project_stats.each do |record| %>
    <tr>
      <td><%= (record.created_at + 8.hours).strftime('%Y/%m/%d') %></td>      
      <td><%= number_with_delimiter(record.revenue) %></td>
      <td><%= record.num_customer %></td>
    </tr>
  <% end %>
</table>
<p>
<%= link_to 'Close',  stats_projects_path %>
</p>
</div>