config/routes.rb
Byop::Application.routes.draw do

  resource :session
  resources :user_menus, :only => [:index]
  resources :manufacturers, :only => [:index, :new, :create, :edit, :update]  
  resources :users do
    resources :user_levels
  end
  resources :customers do
    resources :comm_logs, :only => [:new, :create, :show, :destroy]
  end
  resources :src_plants
  resources :suppliers
  resources :quality_issues, :only  => [:index]
  resources :shipment, :only => [:index]
  resources :projects do
    member do
      put :cancel
      put :re_activate
    end
    collection do
      get :search
      put :search_results
      get :stats
      put :stats_results
    end
    resources :project_logs, :only => [:new, :create, :show, :destroy]
    resources :productions, :only => [:index, :new, :create, :edit, :update, :show]
    resources :shipments, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
      end
    end
    
    resources :sourcings, :only => [:index, :new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :purchasings, :only => [:index, :new, :create, :edit, :update, :show, :destroy] do
      member do
        put :approve
        put :dis_approve
        put :re_approve
        put :stamp
      end

    end
    resources :installations, :only => [:index, :new, :create, :edit, :update] 
    resources :proj_modules, :only => [:new, :create]
    resources :quality_issues, :only => [:new, :create, :edit, :update, :show] 
  end  

  resources :productions do
    resources :production_logs, :only => [:index, :new, :create]
  end
  
  resources :payment_logs, :only =>[:index]
  resources :purchasings do
    collection do
      get :search
      put :search_results
    end     
    resources :purchasing_logs, :only => [:index, :new, :create] 
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  
  resources :sourcings do
    collection do
      get :search
      put :search_results
    end      
    resources :sourcing_logs, :only => [:index, :new, :create]   
    resources :payment_logs, :only => [:index, :new, :create, :edit, :update, :show]
  end
  resources :payment_logs do
    resources :pay_status_logs, :only => [:new, :create]
    member do
      put :approve
      put :stamp_paid
    end
    collection do
      get :search
      put :search_results      
      get :stats
      put :stats_results
    end  
  end
  
  resources :installation_purchases, :only => [:index]  
  resources :installations do
    resources :installation_logs, :only => [:index, :new, :create]
    resources :installation_purchases, :only => [:new, :create, :edit, :update, :show] do
      member do
        put :approve
        put :dis_approve
        put :re_approve        
      end
    end          
  end  
  
  resources :installation_purchases do
    member do
      put :warehousing
    end
    resources :installation_purchase_logs, :only => [:new, :create]
  end  
  
  resources :parts do
    resources :out_logs, :only => [:new, :create, :show]
  end
  
  resources :shipments do
    resources :shipment_items, :only => [:index]
  end
  
  resources :shipment_items do
    resources :box_items
  end
  resources :sys_logs, :only => [:index] do
    collection do
      get :sort_by_user_id
      get :sort_by_ip
    end
  end   
  
  root :to => "sessions#new"
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/user_menus', :to => 'user_menus#index'
  match '/view_handler', :to => 'application#view_handler'

end

app/models/sourcing.rb
# encoding: utf-8
class Sourcing < ActiveRecord::Base
  
  attr_accessor :proj_name, :total
  
  attr_accessor   :project_id_search, :start_date_search, :end_date_search, :approved_by_vp_eng_search, :completed_search,
                  :approved_by_ceo_search, :eng_id_search, :src_plant_id_search, :src_eng_id_search, :customer_id_search
                  
  
  attr_accessible :project_id_search, :start_date_search, :end_date_search,  :approved_by_vp_eng_search, :completed_search,
                  :approved_by_ceo_search, :eng_id_search, :src_plant_id_search, :src_eng_id_search, :customer_id_search,
                  :as => :role_search_stats
                  
  attr_accessible :prod_name, :part_num, :spec, :qty, :unit, :unit_price, :proj_module_id, :src_plant_id, :start_date, :finish_date, :src_eng_id, :project_id, :total,
                  :as => :role_new
  attr_accessible :prod_name, :part_num, :spec, :qty, :unit, :unit_price, :proj_module_id, :src_plant_id, :start_date, :finish_date, :src_eng_id,
                  :completed, :total, :src_plant_id,  
                  :as => :role_update 
  attr_accessible :approved_by_vp_eng, :approve_vp_eng_id, :approve_date_vp_eng, 
                  :approved_by_ceo, :approve_ceo_id, :approve_date_ceo, :stamped,
                  :as => :role_approve_stamp               
                  
  #has_and_belongs_to_many :categories
  belongs_to :input_by, :class_name => 'User' 
  belongs_to :eng, :class_name => 'User'
  belongs_to :src_eng, :class_name => 'User'
  belongs_to :src_plant, :class_name => 'SrcPlant'
  belongs_to :approve_vp_eng, :class_name => 'User', :foreign_key => 'approve_vp_eng_id'
  belongs_to :approve_ceo, :class_name => 'User', :foreign_key => 'approve_ceo_id'  
  belongs_to :project
  has_many :sourcing_logs
  has_many :proj_modules
  has_many :payment_logs
  
  validates :prod_name, :presence => true, :uniqueness => {:scope => :project_id, :message => '同一项目外协件不能重名！' }
  validates_numericality_of :project_id, :greater_than => 0
  validates :spec, :presence => true
  validates :qty, :numericality => { :only_integer => true } 
  validates :unit, :presence => true
  validates :start_date, :presence => true
  validates :finish_date, :presence => true
  
  def find_sourcings
    sourcings = Sourcing.where("sourcings.created_at > ?", 6.years.ago)
    sourcings = sourcings.where('start_date > ?', start_date_search) if start_date_search.present?
    sourcings = sourcings.where('start_date < ?', end_date_search) if end_date_search.present?
    sourcings = sourcings.joins(:project).where('projects.customer_id = ?', customer_id_search) if customer_id_search.present?
    sourcings = sourcings.where('project_id = ?', project_id_search) if project_id_search.present? 
    sourcings = sourcings.where('src_plant_id = ?', src_plant_id_search) if src_plant_id_search.present? 
    sourcings = sourcings.where('eng_id = ?', eng_id_search) if eng_id_search.present?
    sourcings = sourcings.where('src_eng_id = ?', src_eng_id_search) if src_eng_id_search.present?
    sourcings = sourcings.where('sourcings.completed = ?', true) if completed_search.present? && completed_search == 'true'
    sourcings = sourcings.where('sourcings.completed = ? OR sourcings.completed IS NULL', false) if completed_search.present? && completed_search == 'false'    
    sourcings = sourcings.where("approved_by_vp_eng = ?", true) if approved_by_vp_eng_search.present? && approved_by_vp_eng_search == 'true'
    sourcings = sourcings.where('approved_by_vp_eng = ? OR approved_by_vp_eng IS NULL', false) if approved_by_vp_eng_search.present? && approved_by_vp_eng_search == 'false'
    sourcings = sourcings.where('approved_by_ceo = ?', true) if approved_by_ceo_search.present? && approved_by_ceo_search == 'true'
    sourcings = sourcings.where('approved_by_ceo = ? OR approved_by_ceo IS NULL', false) if approved_by_ceo_search.present? && approved_by_ceo_search == 'false'
    sourcings
  end
  
end
   

app/controllers/sourcings_controller.rb
# encoding: utf-8
class SourcingsController < ApplicationController
  before_filter :require_signin
  before_filter :require_employee  
  
  helper_method :has_create_right?, :has_show_right?, :has_update_right?, :has_log_right?,
                :need_approve?, :has_stats_right?, :display_approve?, :display_dis_approve?
  
  def index
    @title = '外协计划'
    @project = Project.find(params[:project_id])
    @sourcings = @project.sourcings.order("completed, created_at DESC, start_date, finish_date").paginate(:per_page => 40, :page => params[:page])    
  end

  def new
    @title = '输入计划'
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.new()
    if !has_create_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end

  def create
    if has_create_right?
      @project = Project.find(params[:project_id])
      @sourcing = @project.sourcings.new(params[:sourcing], :as => :role_new)
      @sourcing.input_by_id = session[:user_id]
      if @sourcing.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=计划已保存！")
      else
        flash.now[:error] = '数据错误，无法保存！'
        render 'new'
      end
    end
  end

  def edit
    @title = '更改计划'
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.find(params[:id])
    if !has_update_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
=begin
    if @sourcing.approved_by_ceo 
      flash.now[:error] = '外协已批准，无法更新!'
      render 'edit'
    end
=end
  end

  def update
    if has_update_right?
      @project = Project.find(params[:project_id])
      @sourcing = @project.sourcings.find(params[:id])
      @sourcing.input_by_id = session[:user_id]
      unless @sourcing.approved_by_ceo 
        if @sourcing.update_attributes(params[:sourcing], :as => :role_update)
           redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=计划已更改！")
        else
          flash.now[:error] = '数据错误，无法保存!'
          render 'edit'
        end
      else
        flash.now[:error] = '外协已批准，无法更新!'
        render 'edit'
      end
    end
  end

  def show
    @title = '外协计划内容'
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.find(params[:id])
    if !has_show_right?
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足！")
    end
  end

  def approve
    
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.find(params[:id])
    if need_approve?(@sourcing)  
      if vp_eng?
        @sourcing.update_attributes({:approved_by_vp_eng => true, :approve_vp_eng_id => session[:user_id],
                                       :approve_date_vp_eng => Time.now}, :as => :role_approve_stamp)

      elsif ceo?
        @sourcing.update_attributes({:approved_by_ceo => true, :approve_ceo_id => session[:user_id],
                                    :approve_date_ceo => Time.now}, :as => :role_approve_stamp) 
      end
    
      redirect_to project_sourcing_path(@project, @sourcing), :notice => '外协已批准！'
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!")    
    end
  end

  def dis_approve
    
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.find(params[:id])
    if need_approve?(@sourcing) 
      if vp_eng?
        @sourcing.update_attributes({:approved_by_vp_eng => false, :approve_vp_eng_id => session[:user_id],
                                       :approve_date_vp_eng => Time.now}, :as => :role_approve_stamp)
      elsif ceo?
        @sourcing.update_attributes({:approved_by_ceo => false, :approve_ceo_id => session[:user_id],
                                    :approve_date_ceo => Time.now}, :as => :role_approve_stamp) 
      end
    
      redirect_to project_sourcing_path(@project, @sourcing), :notice => '外协已否决！'
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!")    
    end
  end

  def re_approve
    
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.find(params[:id])
    if ceo?  
      @sourcing.update_attributes({:approved_by_ceo => nil, :approve_ceo_id => nil, :approve_date_ceo => nil,
                                   :approved_by_vp_eng => nil, :approve_vp_eng_id => nil, :approve_date_vp_eng => nil},
                                   :as => :role_approve_stamp)
    
      redirect_to project_sourcing_path(@project, @sourcing), :notice => '外协需要重新批准！'
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!")    
    end
  end
  
  def stamp
    @project = Project.find(params[:project_id])
    @sourcing = @project.sourcings.find(params[:id])
    if comp_sec?  
      @sourcing.update_attributes({:stamped => true }, :as => :role_approve_stamp)
    
      redirect_to project_sourcing_path(@project, @sourcing)
    else
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=权限不足!")    
    end    
  end
  
  def search
    @sourcing = Sourcing.new
  end

  def search_results
    @sourcing = Sourcing.new(params[:sourcing], :as => :role_search_stats)
    @sourcings = @sourcing.find_sourcings.order("project_id DESC, created_at DESC, start_date") #.paginate(:per_page => 40, :page => params[:page])
    #seach params
    @search_params = search_params()
  end  
        
  protected
  
  def need_approve?(sourcing)
    if vp_eng? && sourcing.approved_by_ceo.nil?
      return true
    elsif ceo? && sourcing.approved_by_vp_eng 
      return true
    end
    return false
  end 
  
  def display_approve?(sourcing)
    if vp_eng? && (sourcing.approved_by_vp_eng.nil? || !sourcing.approved_by_vp_eng)
      return true
    elsif ceo? && (sourcing.approved_by_ceo.nil? || !sourcing.approved_by_ceo)
      return true
    end
    return false
  end
  
  def display_dis_approve?(sourcing)
    if vp_eng? && (sourcing.approved_by_vp_eng.nil? || sourcing.approved_by_vp_eng)
      return true
    elsif ceo? && (sourcing.approved_by_ceo.nil? || sourcing.approved_by_ceo)
      return true
    end
    return false
  end 
  
  def has_approve_right?
     ceo?  || vp_eng? 
  end
    
  def has_show_right?
    is_eng? || acct? || comp_sec? || vp_sales? || coo? || ceo? || vp_eng? 
  end
  
  def has_create_right?
    src_eng?  || ceo? || vp_eng?
  end
  
  def has_update_right?
    src_eng? || ceo? || vp_eng? 
  end
  
  def has_log_right?
    src_eng? || comp_sec? || vp_sales? || coo? || ceo?  || vp_eng?
  end

  def has_stats_right?  #show stats on search page
    src_eng? || vp_sales? || coo? || ceo? || vp_eng? 
  end
  
  def search_params
    search_params = "参数："
    search_params += ' 开始日期：' + params[:sourcing][:start_date_search] if params[:sourcing][:start_date_search].present?
    search_params += ', 结束日期：' + params[:sourcing][:end_date_search] if params[:sourcing][:end_date_search].present?
    search_params += ', 客户 ：' + Customer.find_by_id(params[:sourcing][:customer_id_search].to_i).short_name if params[:sourcing][:customer_id_search].present? 
    search_params += ', 项目 ：' + Project.find_by_id(params[:sourcing][:project_id_search].to_i).name if params[:sourcing][:project_id_search].present?   
    search_params += ', 工程师：' + User.find_by_id(params[:sourcing][:eng_id_search].to_i).name if params[:sourcing][:eng_id_search].present?
    search_params += ', 外协工程师：' + User.find_by_id(params[:sourcing][:src_eng_id_search].to_i).name if params[:sourcing][:src_eng_id_search].present?
    search_params += ', 外协厂：' + SrcPlant.find_by_id(params[:sourcing][:src_plant_id_search].to_i).name if params[:sourcing][:src_plant_id_search].present?
    search_params += ', 完成？ ：' + params[:sourcing][:completed_search] if params[:sourcing][:completed_search].present?
    search_params += ', 副总批了？ ：' + params[:sourcing][:approved_by_vp_eng_search] if params[:sourcing][:approved_by_vp_eng_search].present?
    search_params += ', 厂长批了？ ：' + params[:sourcing][:approved_by_ceo_search] if params[:sourcing][:approved_by_ceo_search].present?
    search_params
  end
  
end

app/helpers/sourcings_helper.rb
module SourcingsHelper
end

app/views/sourcings/create.html.erb
<h1>Sourcings#create</h1>
<p>Find me in app/views/sourcings/create.html.erb</p>

app/views/sourcings/edit.html.erb
<div id='main_body'>
	<h1>修改外协件内容</h1>
	<%= render 'form' %>
	<%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
</div>

app/views/sourcings/index.html.erb
<div id="main_body">
<h1>外协计划-<%=@project.name %></h1>
<div class="byop_pagination"><%= will_paginate %></div>
<table>
  <tr>
    <th>#</th>
    <th>生成日期</th>
    <th>产品名称</th>
    <th>客户</th>
    <th>开工日期</th>
    <th>完成日期</th>
    <th>批准</th>
    <th>完成</th>
    <th>外协厂</th>
    <th>部件工程师</th>
    <th>外协工程师</th>
    <th></th>
    <th></th> 
    <th></th>
  </tr>

<% @sourcings.each do |src| %>
  <tr>
  	<td><%= link_to src.id.to_s, SUBURI + "/view_handler?index=1&url=#{project_sourcing_path(@project, src)}" if has_show_right? %><%='*' if (src.created_at + 8.hours) > DAYS_OF_NEW.days.ago %></td>
  	<td><%= (src.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
    <td><%= src.prod_name %></td>
    <td width='10%'><%= src.project.customer.short_name %></td>
    <td><%= src.start_date.strftime("%Y/%m/%d") %></td>
    <td><%= src.finish_date.strftime("%Y/%m/%d") %></td>
    <td><%= yes_no_cn(src.approved_by_vp_eng && src.approved_by_ceo) %></td>
    <td><%= yes_no_cn(src.completed) %></td>
    <td width="10%"><%= src.src_plant.short_name if src.src_plant_id.present? %></td>
    <td><%= src.eng.name unless src.eng_id.blank? %></td>
    <td><%= src.src_eng.name unless src.src_eng_id.blank? %></td>  
    <td><%= link_to 'Edit', SUBURI + "/view_handler?index=1&url=#{edit_project_sourcing_path(@project, src)}" if has_update_right? %></td>
    <td><%= link_to '批准', approve_project_sourcing_path(@project, src), :method => :put if need_approve?(src) && display_approve?(src) %></td>
    <td><%= link_to '状态', SUBURI + "/view_handler?index=1&url=#{sourcing_sourcing_logs_path(src)}" %></td>
  </tr>
<% end %>
</table>
  <%= link_to 'Back', SUBURI + "/view_handler?index=0" %>
  &nbsp;<%= link_to '输入外协', SUBURI + "/view_handler?index=1&url=#{new_project_sourcing_path(@project)}" if has_create_right? %>
  <%= link_to '搜索', search_sourcings_path %>
</div>

app/views/sourcings/new.html.erb
<div id='main_body'>
	<h1>输入外协件</h1>
	<%= render 'form_new' %>
	<%= link_to 'Back', SUBURI + "/view_handler?index=0"%>
</div>

app/views/sourcings/search_results.html.erb
<div id="main_body">
<h1>外协计划搜索内容 </h1>
<%=@search_params%>
<% if has_stats_right? %>
<p>总外购产品个数： <%=@sourcings.count %>, 
	总金额￥： <%= number_with_delimiter(number_with_precision(@sourcings.sum('unit_price * qty'), :precision => 2)) %>,
	待批准产品个数： <%= @sourcings.where("approved_by_vp_eng IS NULL OR approved_by_ceo IS NULL").count %>, 
	未批准产品个数： <%= @sourcings.where("approved_by_vp_eng = ? OR approved_by_ceo =?", false,false).count %>,
         责任工程师数： <%= @sourcings.select("DISTINCT(eng_id)").count %>, </p>
<p>	已交货个数： <%= @sourcings.where('sourcings.completed = ?', true).count  %>,
	已交货金额￥： <%= number_with_delimiter(number_with_precision(@sourcings.where('sourcings.completed = ?', true).sum('unit_price * qty'), :precision => 2))  %>,	
	未交货个数： <%= @sourcings.where('sourcings.completed = ?', false).count  %>,
	未交货金额￥： <%= number_with_delimiter(number_with_precision(@sourcings.where('sourcings.completed = ?', false).sum('unit_price * qty'), :precision => 2))  %>,
	已支付金额￥：<%= number_with_delimiter(number_with_precision(@sourcings.joins(:payment_logs).where('payment_logs.paid = ?', true).sum('payment_logs.amount'), :precision => 2)) %>
	未支付金额￥：<%=number_with_delimiter(number_with_precision(@sourcings.sum('unit_price * qty').to_f - @sourcings.joins(:payment_logs).where('payment_logs.paid = ?', true).sum('payment_logs.amount').to_f, :precision => 2)) %>		 
<p>	外协厂个数： <%= @sourcings.select("DISTINCT(src_plant_id)").count %>,          
</p>
<% end %>
<table>
  <tr>
    <th>#</th>
    <th>生成日期</th>
    <th>产品名称</th>
    <th>客户</th>
    <th>项目名称</th>
    <th>开工日期</th>
    <th>完成日期</th>
    <th>批准</th>
    <th>完成</th>
    <th>部件工程师</th>
    <th>外协工程师</th>
    <th></th>
    <th></th> 
    <th></th>
  </tr>

<% @sourcings.each do |src| %>
  <tr>
  	<td><%= link_to src.id.to_s, SUBURI + "/view_handler?index=1&url=#{project_sourcing_path(src.project, src)}" if has_show_right? %><%='*' if (src.created_at + 8.hours) > DAYS_OF_NEW.days.ago %></td>
  	<td><%= (src.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
    <td><%= src.prod_name %></td>
    <td width="10%"><%= src.project.customer.short_name %></td>
    <td><%= src.project.name %></td>
    <td><%= src.start_date.strftime("%Y/%m/%d") %></td>
    <td><%= src.finish_date.strftime("%Y/%m/%d") %></td>
    <td><%= src.approved_by_vp_eng && src.approved_by_ceo %></td>
    <td><%= src.completed %></td>
    <td><%= src.eng.name unless src.eng_id.blank? %></td>
    <td><%= src.src_eng.name unless src.src_eng_id.blank? %></td>  
    <td><%= link_to 'Edit', SUBURI + "/view_handler?index=1&url=#{edit_project_sourcing_path(src.project, src)}" if has_update_right? %></td>
    <td><%= link_to '批准', approve_project_sourcing_path(src.project, src), :method => :put if need_approve?(src) %></td>
    <td><%= link_to '状态', SUBURI + "/view_handler?index=1&url=#{sourcing_sourcing_logs_path(src)}" %></td>
  </tr>
<% end %>
</table>
  <%= link_to 'Back', search_sourcings_path %>
  <!--&nbsp;<%= link_to '输入外协', SUBURI + "/view_handler?index=1&url=#{new_project_sourcing_path(src.project)}" if has_create_right? %-->

</div>

app/views/sourcings/show.html.erb
<div id="main_body">

<h1>计划内容-<%=@sourcing.prod_name %></h1>

<p>
  <b>名称:</b>
  <%= @sourcing.prod_name %>
</p>
<p>
  <b>零件#:</b>
  <%= @sourcing.part_num %>
</p>
<p>
  <b>规格:</b>
  <%= @sourcing.spec %>
</p>
<p>
  <b>数量/单位:</b>
  <%= @sourcing.qty %><%= @sourcing.unit %>
</p>
<p>
  <b>单价（￥）:</b>
  <%= @sourcing.unit_price %>
</p>
<p>
  <b>总金额（￥）:</b>
  <%= number_with_precision(@sourcing.unit_price * @sourcing.qty, :precision => 2) if @sourcing.unit_price.present? && @sourcing.qty.present? %>
</p>
<p>	
  <b>已支付额（￥）:</b>
  <%= number_with_precision(@sourcing.payment_logs.where('paid = ?', true).sum("amount"), :precision => 2) %>
</p>
<p>
  <b>盖章？：</b>
  <%= yes_no_cn(@sourcing.stamped) %>
</p>
<p>
  <b>外协厂:</b>
  <%= @sourcing.src_plant.name if @sourcing.src_plant_id.present? %>
</p>
<p>
  <b>责任工程师:</b>
  <%= @sourcing.eng.name if @sourcing.eng_id.present? %>
</p>
<p>
  <b>完成：</b>
  <%= yes_no_cn(@sourcing.completed) %>
</p>
<p>
  <b>开工日期:</b>
  <%= @sourcing.start_date.strftime("%Y/%m/%d") %>
</p>
<p>
  <b>完成日期:</b>
  <%= @sourcing.finish_date.strftime("%Y/%m/%d") %>
</p>

<p>
  <b>工程付总批准:</b>
  <%= yes_no_cn(@sourcing.approved_by_vp_eng) %>
</p>
<p>
  <b>审批人:</b>
  <%= @sourcing.approve_vp_eng.name if @sourcing.approve_vp_eng_id.present? && @sourcing.approve_vp_eng_id > 0 %>
</p>
<p>
  <b>审批日期:</b>
  <%= @sourcing.approve_date_vp_eng.strftime("%Y/%m/%d") unless @sourcing.approve_date_vp_eng.nil? %>
</p>
<p>
  <b>厂长批准:</b>
  <%= yes_no_cn(@sourcing.approved_by_ceo) %>
</p>
<p>
  <b>审批人:</b>
  <%= @sourcing.approve_ceo.name if @sourcing.approve_ceo_id.present? && @sourcing.approve_ceo_id > 0 %>
</p>
<p>
  <b>审批日期:</b>
  <%= @sourcing.approve_date_ceo.strftime("%Y/%m/%d") unless @sourcing.approve_date_ceo.nil? %>
</p>
<p>
  <b>输入/更改人:</b>
  <%= @sourcing.input_by.name %>
</p>
<p>
  <b>状态Log:</b>	
  <ul>
<% @sourcing.sourcing_logs.order("id DESC").each do |f| %>
  <li>
  <%= link_to f.created_at.strftime("%Y-%m-%d").to_s + ', ' + f.input_by.name + ', '+ f.log[0..40], SUBURI + "/view_handler?index=1&url=#{sourcing_sourcing_logs_path(f.sourcing_id, f.id)}" %>
  </li>
<% end %>
</ul>
</p>

<%= link_to 'Back', SUBURI + "/view_handler?index=0", :id => 'close' %>
<%= link_to '批准', approve_project_sourcing_path(@project, @sourcing), :method => :put, :id => 'sourcing_need_approve', :confirm => '批准外协' + @sourcing.prod_name + '?' if need_approve?(@sourcing) && display_approve?(@sourcing) %>
<%= link_to '否决', dis_approve_project_sourcing_path(@project, @sourcing), :method => :put, :id => 'sourcing_need_dis_approve', :confirm => '否决外协' + @sourcing.prod_name + '?' if need_approve?(@sourcing) && display_dis_approve?(@sourcing) %>
<%= link_to '盖章', stamp_project_sourcing_path(@project, @sourcing), :method => :put , :id => 'sourcing_stamp', :confirm => '盖章外协' + @sourcing.prod_name + '?' if comp_sec? && !@sourcing.stamped %>
<%= link_to '重新外协', re_approve_project_sourcing_path(@project, @sourcing), :method => :put, :id => 'sourcing_need_re_approve', :confirm => '重新外协' + @sourcing.prod_name + '?' if ceo? %>
<%= link_to '付款记录', sourcing_payment_logs_path(@sourcing), :id => 'sourcing_payment_log' if src_eng? || comp_sec? || vp_eng? || coo? || vp_sales? || ceo? %>
<%= link_to '输入Log', new_sourcing_sourcing_log_path(@sourcing, :format => :js), :remote => true, :id => 'new_log_link' if has_log_right? %>

</div>

app/views/sourcings/update.html.erb
<h1>Sourcings#update</h1>
<p>Find me in app/views/sourcings/update.html.erb</p>